[main]
# Путь к директории с входными CSV-файлами
input = "./examples/input"

# Путь для выходных файлов (опционально)
output = "./output"

# Список масок для фильтрации файлов
filename_mask = ["level", "trade"]